NR<-read.table("seqlenNR.txt")
NR<-as.numeric(unlist(NR))
hist(NR, xlab="long non coding RNA seq length", main="frequency", col="lightgreen", xlim=c(0,10000))
hist(NR, xlab="long non coding RNA seq length", main="frequency", col="lightgreen", xlim=c(0,10000), breaks=100)
hist(NR, xlab="long non coding RNA seq length", main="frequency", col="lightgreen", xlim=c(0,10000), breaks=10)
hist(NR, xlab="long non coding RNA seq length", main="frequency", col="lightgreen", xlim=c(0,10000), breaks=1000)
NM<-read.table("seqlenNM.txt")
NM<-as.numeric(unlist(NM))
hist(NM, xlab="mRNA seq length", main="frequency", col="lightblue", xlim=c(0,15000), breaks=200)
hist(NR, xlab="non coding RNA seq length", main="frequency", col="lightgreen", xlim=c(0,10000), breaks=200)
hist(NR, xlab="non coding RNA seq length", main="frequency", col="lightgreen", xlim=c(0,10000), breaks=200,freq = FALSE)
hist(NM, xlab="mRNA seq length", main="frequency", col="lightblue", xlim=c(0,15000), breaks=200, freq = FALSE)
